# Generated by Django 3.1.1 on 2020-09-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
    ]
